### ISSUE TITLE
Issues with the install

### ISSUE THREAD

**Issue by V4nkor** [minneyar/clementine-discord#1]
I am currently on a windows 10 computer. I managed to install pypresence with PyPi, but I can't seem to install dbus with PyPi, or with the Dbus master.
This makes me unable to use "clementine_discord.py"
As a beginner with installing and using python projects and using github, I'm sure this issue is really simple. Sorry for the inconvenience.

**Comment by pjreed** [comment]
Unfortunately, I don't think this will work with Windows; dbus is a Linux interprocess communication system.

This program really just uses dbus because it's a convenient way to control Clementine, though, and if there's some other kind of inter-process communication mechanism or a command line interface that works on Windows, it might be pretty straightforward to make it use that instead.
